[tools]
ruby = "latest"


[env]
GEM_HOME="{{config_root}}/.gems"
BUNDLE_BIN="{{env.GEM_HOME}}/bin"
_.path = [
    "{{env.BUNDLE_BIN}}",
    "{{config_root}}/node_modules/.bin",
]


[tasks.serve]
run = """jekyll serve --livereload"""

[tasks."build:js"]
run = """parcel build"""
sources = ['package.json', '_scripts/*']
outputs = ['assets/js']