name = "hephaestus"
description = "Modern and minimalistic blog theme"
min_version = "0.14.0"
license = "MIT"
homepage = "https://github.com/vhdirk/hephaestus"
demo = "https://vhdirk.github.io/hephaestus"

[author]
name = "vhdirk"
homepage = "https://github.com/vhdirk"

# Any variable here can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
outdate_callout = false

toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
comment = false